apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: epaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: your-docker-registry/payment-service:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: microservice-config
        - secretRef:
            name: db-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: epaas
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
