emit:
  - "@typespec/openapi3"
  - "@typespec/http-client-java"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}/schema"
    openapi-versions:
      - 3.1.0
  "@typespec/http-client-java":
    emitter-output-dir: "{output-dir}/clients/java"
